name: Build And Push Image via Golang Application Hello World

env:

  DOCKER_USERNAME: sanvu
  DOCKER_PASSWORD: ${{ secrets.PASS1 }}
  IMAGE_TAG: ${{ github.sha }}

on:
  push:
    branches:
      - master

jobs:
  build_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Binary
        run: go build -o main .

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact-golang
          path: ./main

  build_push_image:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: artifact-golang
          path: ./main

      - name: Docker Login
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: Docker Build
        run: docker build -f ./go/Dockerfile -t ${DOCKER_USERNAME}/testmerge/go:${IMAGE_TAG}

      - name: docker push
        run: docker push ${DOCKER_USERNAME}/testmerge/go:${IMAGE_TAG} 
