name: ci

env:
  DOCKER_USERNAME: sanvu
  DOCKER_PASSWORD: ${{ secrets.PASS1 }}
  IMAGE_TAG: ${{ github.sha }}

on:
  push:
    branches:
      - main

jobs:
  build_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build jar
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact-java
          path: ./target/*.jar

  build_push_image:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: artifact-java
          path: ./*.jar

      - uses: actions/checkout@v4
      - name: Docker Login
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: Docker Build
        run: docker build -f ./java/Dockerfile -t ${DOCKER_USERNAME}/testmerge/java:${IMAGE_TAG}

      - name: docker push
        run: docker push ${DOCKER_USERNAME}/testmerge/java:${IMAGE_TAG}
